@host = http://localhost:5277

POST {{host}}/workspace
Content-Type: application/json

{
  "id": "22371a1d-8420-4c5c-a200-8c6ab14e1e8f",
  "name": "workspace1",
  "email": "your@email.com"
}

###

GET {{host}}/workspace/22371a1d-8420-4c5c-a200-8c6ab14e1e8f
Accept: application/json

###

POST {{host}}/workspace/22371a1d-8420-4c5c-a200-8c6ab14e1e8f/notes
Content-Type: application/json

{
  "id": "9",
  "workspaceId": "22371a1d-8420-4c5c-a200-8c6ab14e1e8f",
  "order": "9",
  "title": "New Note",
  "date": "2024-10-10T10:00:00Z",
  "content": "This is the content of the new note.",
  "color": "blue"
}

###

GET {{host}}/workspace/22371a1d-8420-4c5c-a200-8c6ab14e1e8f/notes
Accept: application/json


###

GET {{host}}/workspace/22371a1d-8420-4c5c-a200-8c6ab14e1e8f/notes/9
Accept: application/json

###
